name: Build and Deploy Vite React App

on:
  push:
    branches:
      - main  # Trigger the action on push to the main branch
  pull_request:
    branches:
      - main  # Trigger the action on PR to the main branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Check out the repository
      - name: Checkout code
        uses: actions/checkout@v2

      # Step 2: Set up the latest Node.js version
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 'node'  # This will automatically use the latest stable version of Node.js

      
      # Step 3: Install dependencies
      - name: Install dependencies
        run: npm install

      # Step 4: Generate Storybook Documentation
      - name: Build Storybook
        run: npm run storybook:build

      # Step 5: Build the Vite app
      - name: Build Vite app
        run: npm run build
