name: Build and Deploy Vite React App

on:
  push:
    branches:
      - main  # Trigger the action on push to the main branch
  pull_request:
    branches:
      - main  # Trigger the action on PR to the main branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Check out the repository
      - name: Checkout code
        uses: actions/checkout@v2

      # Step 2: Set up the latest Node.js version
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 'node'  # This will automatically use the latest stable version of Node.js

      # Step 3: Install dependencies
      - name: Install dependencies
        run: npm install

      # Step 4: Build the Vite app
      - name: Build Vite app
        run: npm run build

      # Step 5: Upload Build Artifacts
      - name: Upload build artifact
        uses: actions/upload-artifact@v3
        with:
          name: vite-build
          path: dist/
      
      # Step 6: Debugging: List files in dist folder
      - name: List files in dist folder
        run: ls -al ./dist

      # Step 7: Deploy to Vercel
      - name: Deploy to Vercel
        env:
          VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
          VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
        run: |
          for file in ./dist/*; do
            curl -X POST https://api.vercel.com/v12/now/deployments \
              -H "Authorization: Bearer $VERCEL_TOKEN" \
              -F "files=@$file" \
              -F "name=preview-${GITHUB_SHA}" \
              -F "target=preview" \
              -F "projectId=$VERCEL_PROJECT_ID"
          done     
      # Step 6: Deploy to Vercel
      # - name: Deploy to Vercel
      #   env:
      #     VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
      #     VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
      #   run: |
      #     curl -X POST https://api.vercel.com/v12/now/deployments \
      #       -H "Authorization: Bearer $VERCEL_TOKEN" \
      #       -F "files=@./dist/*" \
      #       -F "name=preview-${GITHUB_SHA}" \
      #       -F "target=preview" \
      #       -F "projectId=$VERCEL_PROJECT_ID"


      # Step 5: Deploy to GitHub Pages (optional)
      # Uncomment if deploying to GitHub Pages
      # - name: Deploy to GitHub Pages
      #   uses: JamesIves/github-pages-deploy-action@v4
      #   with:
      #     branch: gh-pages  # The branch to deploy to
      #     folder: dist  # The folder to deploy
